[tool.black]
line-length = 80
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env  # Исключаем каталог env
)/
'''

[tool.isort]
include_trailing_comma = true
line_length = 80
lines_after_imports = 2